### ISSUE TITLE
Cannot add REST API URLs. The done button becomes disabled.

### ISSUE THREAD

**Issue by NisugaJ** [IgniteUI/app-builder#10]
Installed date: 2022-02-04
App Builder Version: 2022 Jan release

![image](https://user-images.githubusercontent.com/44756803/152467110-bc76205a-a9cd-4f9e-b082-487b09a71175.png)

**Comment by zdrawku** [comment]
Hey @NisugaJ, thank you for reaching out! This problem is logged in our internal issue tracking system (internal ref - bug #13103). We are going to prioritize it and plan it for the upcomming iterations.

**Comment by JeffWeeks-Tilson** [comment]
Same issue but I figured it was due to it being a local API and the app builder being external to my local system. I figured I'd have to mock it up with the canned North Wind db or something and then pull it local and change the code to my local api to test. I'm new so don't know if the local sources worked prior to this issue...

**Comment by zdrawku** [comment]
Hey @JeffWeeks-Tilson 
> I'm new so don't know if the local sources worked prior to this issue
They havent, this is something that we will have to address on our end.

**Comment by boo2022** [comment]
Using publicly hosted data as suggested from support is really not very useful as most people will be creating their own API's hosted within at their company not publicly. I would think that this limitation to will be a great limitation to the majority of clients. Once this is rectified, the product will be awesome!!

Please let me know when I can expect this option to be available.

Thank you.

**Comment by hanastasov** [comment]
Feature will be available in next release of AppBuilder, scheduled to roll out today. Will add a notification here of the release. Documentation about the feature is already available at https://www.infragistics.com/products/appbuilder/help/using-data-in-your-app#using-data-source-from-local-network-sources
