### ISSUE TITLE
Update github without rolling back user changes

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/app-builder#11]
We want to allow the user to introduce modifications in main/master and AppBuilder shouldn't revert them in the next push.

This is a public work duplicate of #13418 (internal)

**Comment by hanastasov** [comment]
Feature will be available in upcoming Release, scheduled to roll out today. Will keep notified. 

Already there is information on:

https://www.infragistics.com/products/appbuilder/help/generate-app/upload-application-to-github#already-pushed-changes-wont-be-overwritten
