### ISSUE TITLE
Roadmap for more components

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/app-builder#13]
Hi

We've used the Indigo studio app for some time, creating simple wireframes for our specifications. Recently I've started to look into further expand this to possible create full prototypes in place of simple wireframes. The app builder seems to be developing in the right direction, but there seems to be a few core components missing. One is chart, and I saw in the roadmap that this is to be included in the current iteration. However, I can't see anything about other important missing components. Above all, the tree grid is missing, but there seems to be quite a few others like hieracical grid and splitter as well. Are these being considered for inclusion soon? I can't see us adopting the app builder before more components are supported.

**Comment by kdinev** [comment]
@Eralmidia Yes, it is! To give you some update on this: chart will be available next week, tree-grid and hierarchical grid are planned for the next iteration. Those are the major ones planned. Together with the major components, we always update with smaller ones, like expansion-panel, tree, accordion, etc.

**Comment by kdinev** [comment]
@radomirchev will pull an update to the roadmap after the features update next week!

**Comment by Eralmidia** [comment]
Excellent, always good news when it's your capable hands 👍 Guess we'll start adopting this tool now then. Looking forward to the next iteration. Also, apologizes in advance as this might result in me adding a few feature request in this repo as well 😄

**Comment by kdinev** [comment]
@Eralmidia Go ahead, log whatever you need!

**Comment by zdrawku** [comment]
@Eralmidia I've updated the Roadmap with more info relevant to the completed itterations that we had and what will be released next week. As for `Going down the road section` we will update it after the current release.
