### ISSUE TITLE
ESF text filter is not working in Preview mode

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/app-builder#21]
## Description  
When I add grid/tree grid and switch to Preview mode, I could not interact with the text filter of ESF

 * browser: chrome, edge, firefox

## Steps to reproduce  

1. Add grid/tree grid
2. Enable ESF
3. Go to preview Mode
4. Try to filter with text filter of ESF

## Attachments  

![AppBuilder Excel Style Filter](https://user-images.githubusercontent.com/52001020/204378931-d2d3f516-b285-42e8-a149-89a493351c32.gif)

**Comment by hanastasov** [comment]
Internal issue #19885 regards the same bug.

**Comment by zdrawku** [comment]
Updating the public bug as "resolved" as well
