### ISSUE TITLE
Cannot Select Endpoints when connecting to Rest API

### ISSUE THREAD

**Issue by ncoleIS** [IgniteUI/app-builder#23]
## Description  
I am attempting to connect to a Swagger REST API json file. I can utilize App Builder's REST API datasource to connect to the Swagger json file URL, but I cannot configure any endpoints. I can _see the endpoints, but not actually select any of them.

![image](https://user-images.githubusercontent.com/123205895/213795752-5c017434-5202-4175-8cb1-2ebe116579c4.png)

 * browser: Microsoft Edge

## Result  
Cannot configure endpoints to test API with App Builder.

## Expected result  
Based on tutorials I've watched for App Builder, the endpoints should all be clickable. I should be able to configure endpoints and experiment with App Builder.

**Comment by zdrawku** [comment]
Hey @ncoleIS, there's a [help topic](https://www.infragistics.com/products/appbuilder/help/using-data-in-your-app#openapi-swagger-endpoints-are-grayed-out) about this. Usually _grayed out endpoint_ means that the endpoint does not have a defined response or that the response type is unsupported. This can happen if your API does not provide enough information to Swagger to create a proper response description.

Please check the topic section for that and let me know if you still experience that problem.
