### ISSUE TITLE
Links in README lead to 404 pages.

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/app-builder#8]
Links in README lead to 404 pages
![MicrosoftTeams-image (56)](https://user-images.githubusercontent.com/14248932/144206763-04c6e429-bbad-4068-a84d-0f624f05481b.png)

**Comment by zdrawku** [comment]
Fixed by [this commit](https://github.com/IgniteUI/app-builder/commit/e475d059dde8b98110a77f08e3c882056e120fce)
