### ISSUE TITLE
[Help page] Flex Layout add new paragraphs

### ISSUE THREAD

**Issue by morbidiam** [IgniteUI/app-builder#9]
Add the short paragraphs included in the file (including the titles) to the App Builder Flex Layout help page. The new texts should be placed above the video

https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EdmBfROjIMBOilKyO3dMFO0B4MtnioZt4uYm2PpxNLz0eQ?e=f8vfJq

**Comment by zdrawku** [comment]
Addressed on 16th with [commit](https://github.com/IgniteUI/app-builder-docfx/commit/c07b8ca13a5fff232d69f034dd4d1aff5ac5c21e)
